### ISSUE TITLE
Customize the version of the component during installation and uninstallation

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/cli#10]
Currently, **CLI** already provides `install`, `uninstall` commands to install and uninstall the OpenFunction and its dependencies.

We also need support for customizing the version of the component during installation, which will facilitate the installation of OpenFunction in different versions of Kubernetes. 

Some solution is as follows:

1. provide a default inventory of dependent component versions for different versions of Kubernetes. By default, the **CLI** will refer to this inventory for installation
2. use environment variables to pass the version of the dependencies that need to be installed
3. because the components (yaml files) used by the `--region-cn` option are currently converted manually and do not match all versions by default, we will add support for component versions based on community demand (e.g., by submitting issues)

**Comment by benjaminhuo** [comment]
We can release cli v0.1.0 when this feature is completed
