### ISSUE TITLE
Replace the default OpenFunction version installed with latest stable release

### ISSUE THREAD

**Issue by benjaminhuo** [OpenFunction/cli#21]
Currently, `ofn install --all` will install v0.4.0 as the default version which should be changed to [the latest stable release](https://api.github.com/repos/OpenFunction/OpenFunction/releases/latest).

Another issue is default installation timeout could be adjusted to 15m

**Comment by benjaminhuo** [comment]
@wenchajun would you help with this?
@tpiperatgod could give you some advice whenever necessary.

**Comment by wenchajun** [comment]
OK，it is my pleasure
