### ISSUE TITLE
Adding flags to get version information

### ISSUE THREAD

**Issue by wenchajun** [OpenFunction/cli#28]
Currently the `ofn` client does not support displaying version information, perhaps we could add a display flag. The users can use specific flags to get information about the version `ofn`,such as `ofn -v ` or  `ofn --version`

**Comment by benjaminhuo** [comment]
Thanks @24sama for this PR.
Looks like we need to adjust the https://github.com/OpenFunction/cli/blob/main/RELEASE.md accordingly such as build after tag
