### ISSUE TITLE
Proposal to adjust cli flags

### ISSUE THREAD

**Issue by benjaminhuo** [OpenFunction/cli#32]
With the fix in https://github.com/OpenFunction/OpenFunction/pull/222, the controller will no longer fail if some CRDs couldn't be found. Looks like this enables flexible use combinations of OpenFunction such as:

- Sync or Async or App Serving only: The image is built in a different env and the user needn't install Shipwright in serving env
- Async function only: Shipwright + Keda + Dapr
- Knative sync function only: Shipwright + Knative + Ingress
- Sync function only: Shipwright + Keda + Keda http + Ingress

So we might need to use switches like:

- From users' perspective:
`--knative-runtime`:  Shipwright + Knative + Ingress
`--async-runtime`:  Shipwright + Keda + Dapr
`--sync-runtime`: Shipwright + Keda + Keda http + Ingress
`--elasticapp-runtime`: Shipwright + Keda + Dapr
`--knative-serving`:  Knative + Ingress
`--async-serving`:  Keda + Dapr
`--sync-serving`:  Keda + Keda http + Ingress
`--elasticapp-serving`: Keda + Dapr

- From a technical's perspective to provide flexibility:
`--knative`
`--dapr`
`--keda`
`--shipwright`
`--keda-http`
`--ingress`

@wanjunlei @tpiperatgod @wenchajun what do you think

**Comment by wanjunlei** [comment]
I think the ingress must be installed. The ingress controller can be specified with `--ingress` such as `--ingress apisix`.

**Comment by tpiperatgod** [comment]
Can `--runtime` also be styled according to @wanjunlei 's suggestion of ingress, as follows:
```
--runtime knative
--runtime async
```

The degree of ingress support may depend on the compatibility of the ingress controller with Kubernetes, I think...

**Comment by benjaminhuo** [comment]
> Can `--runtime` also be styled according to @wanjunlei 's suggestion of ingress, as follows:
> 
> ```
> --runtime knative
> --runtime async
> ```
> 
> The degree of ingress support may depend on the compatibility of the ingress controller with Kubernetes, I think...

That's looks better

**Comment by benjaminhuo** [comment]
Maybe like this:

- From users' perspective:
`--runtime knative`:  Knative + Ingress
`--runtime async`:  Keda + Dapr
`--runtime sync`: Keda + Keda http + Ingress
`--runtime elasticapp`: Keda + Dapr
`--with-ci`: Shipwright
`--ingress nginx`: ingress support

- From a technical's perspective to provide flexibility:
`--with-knative`
`--with-dapr`
`--with-keda`
`--with-shipwright`
`--with-keda-http`

**Comment by tpiperatgod** [comment]
> Maybe like this:
> 
> * From users' perspective:
>   `--runtime knative`:  Knative + Ingress
>   `--runtime async`:  Keda + Dapr
>   `--runtime sync`: Keda + Keda http + Ingress
>   `--runtime elasticapp`: Keda + Dapr
>   `--with-ci`: Shipwright
> * From a technical's perspective to provide flexibility:
>   `--with-knative`
>   `--with-dapr`
>   `--with-keda`
>   `--with-shipwright`
>   `--with-keda-http`
>   `--with-ingress`

Looks good to me.

**Comment by tpiperatgod** [comment]
Here is a matrix diagram of this adjustment: https://hackmd.io/dzNMvL-PSCWelEFea8KNTA?view
