### ISSUE TITLE
Use ofn to get the function's logs

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/cli#36]
Since we use a specific naming template to set the name of the pod in OpenFunction, when users want to check the log of the function, they cannot quickly find the corresponding function pod from the results displayed by `kubectl get po`.

We need to add a `logs` subcommand for this purpose:

```shell
ofn logs <function-name> <pod-name>

ofn logs -f <function-name> <pod-name>
```

**Comment by loheagn** [comment]
Hi, I'm new to openfunction, and I want to take this issue to start to contribute to the openfunction community :)

**Comment by tpiperatgod** [comment]
Hi @loheagn , feel free to work on it and feel free to discuss it if you have any questions at this work. 😀

**Comment by benjaminhuo** [comment]
> loheagn

@loheagn That's great. Welcome to the new contributor!

![image](https://user-images.githubusercontent.com/18525465/167529283-63b5c606-c44f-44aa-9f97-e8702c64844e.png)

**Comment by loheagn** [comment]
> Since we use a specific naming template to set the name of the pod in OpenFunction, when users want to check the log of the function, they cannot quickly find the corresponding function pod from the results displayed by `kubectl get po`.
> 
> We need to add a `logs` subcommand for this purpose:
> 
> ```shell
> ofn logs <function-name> <pod-name>
> 
> ofn logs -f <function-name> <pod-name>
> ```

Hi, @tpiperatgod , what's meaning of `-f` in your proposal?

**Comment by tpiperatgod** [comment]
> > Since we use a specific naming template to set the name of the pod in OpenFunction, when users want to check the log of the function, they cannot quickly find the corresponding function pod from the results displayed by `kubectl get po`.
> > We need to add a `logs` subcommand for this purpose:
> > ```shell
> > ofn logs <function-name> <pod-name>
> > 
> > ofn logs -f <function-name> <pod-name>
> > ```
> 
> Hi, @tpiperatgod , what's meaning of `-f` in your proposal?

Hi @loheagn , the `-f` flag is the same as in `kubectl logs -f` and is used to stream pod logs.

**Comment by loheagn** [comment]
Thanks for reply! @tpiperatgod 

By the way, does the `pod-name` mean the `spec.serving.template.containers.name` in the Function CRD, and also the name of the container in the pod?

**Comment by tpiperatgod** [comment]
> Thanks for reply! @tpiperatgod
> 
> By the way, does the `pod-name` mean the `spec.serving.template.containers.name` in the Function CRD, and also the name of the container in the pod?

You are right and here is some additional information about the two runtimes currently supported in OpenFunction:
- knative runtime
  In this runtime, function pods usually contain 2 to 3 containers with fixed names: `queue-proxy`, `function`, `daprd`
- async runtime
  In this runtime, the function pod usually contains 2 containers with fixed names: `function`, `daprd`

But I don't think we need to validate the \<pod-name\>, we just need to return what `kubectl logs -f` returns. Feel free to share your views. 🙂

**Comment by loheagn** [comment]
Hi, @tpiperatgod , this is my proposal.

The usage of this command should like `ofn logs [OPTIONS] FUNCTION_NAME [CONTAINER_NAME]`. The options are:

```
  -f, --follow             Specify if the logs should be streamed
  -n, --namespace string   Namspace of the function. Default to 'default'.
```

If the `CONTAINER_NAME` is not provided, then `function` will be used.

```mermaid
graph TD
    A[start] --> B(parse the commandline args)
    B --> C(use client-go to get the `Function` object)
    C --> D(get the status of the `Function`)
    D --> E{the status is serving?}
    E --> | YES | F(get the `status.serving.service` as service-name)
    F --> G(use client-go to get the logs of the pods whose labels contain `serving=service-name`)
    G --> H[end]
    E --> | NO | I(echo error message)
    I --> H
```

**Comment by tpiperatgod** [comment]
Agree. But I think you need to get the Serving name from `.status.serving.resourceRef` of the Function, not from `.status.serving.service`. And you don't need to determine whether the status is Serving. 

Here is an example of how to get the logs manually, please refer to: https://github.com/OpenFunction/samples/tree/release-0.6/functions/async/bindings#input-and-output.

**Comment by loheagn** [comment]
Hi, @tpiperatgod , I opened a PR #46 to fix this issue.

Looking forward to your review :)

**Comment by tpiperatgod** [comment]
> Hi, @tpiperatgod , I opened a PR #46 to fix this issue.
> 
> Looking forward to your review :)

Great! I approved it.
