### ISSUE TITLE
Optimized installation approach

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/cli#4]
We need to improve the way OpenFunction is installed and deployed.

Integrating them into cli project would be a better solution.

**Comment by tpiperatgod** [comment]
I am considering adding three new subcommands to the `fn` command controller:

- install, deploy OpenFunction itself and its dependencies (i.e. fn install <args... >) 
- uninstlal, uninstall OpenFunction itself and its dependencies (i.e. fn uninstall <args... >) 
- demo, a quick demostrate of OpenFunction (i.e. fn demo <args... >) 

## Install

### Scope

`fn install` will work on v0.4.0 and later versions with the following scope:

- Install OpenFunction's dependencies
- Install OpenFunction

### Parameter specifications

> When the following parameters of type bool are used, this means that the setting is true

| Name              | Type   | Description                                                  |
| ----------------- | ------ | ------------------------------------------------------------ |
| --verbose         | bool   | Show verbose information                                     |
| --dapr            | bool   | Using this parameter means that Dapr needs to be installed   |
| --keda            | bool   | Using this parameter means that KEDA needs to be installed   |
| --knative-serving | bool   | Using this parameter means that Knative Serving(and default gateway Kourier) needs to be installed |
| --shipwright      | bool   | Using this parameter means that ShipWright needs to be installed |
| --cert-manager    | bool   | Using this parameter means that Cert Manager needs to be installed |
| --ingress         | bool   | Using this parameter means that Ingress Nginx needs to be installed |
| --openfuncasync   | bool   | Equivalent to --dapr --keda                                  |
| --all             | bool   | Equivalent to --dapr --keda --knative-serving --shipwright --cert-manager --ingress |
| --region-cn       | bool   | For users in China to speed up the download process of dependent components |
| --version         | string | Specify the version of OpenFunction that needs to be installed |
| --dry-run         | bool   | Used to prompt for the components and their versions to be installed by the current command |

### Example

- Install all dependencies and OpenFunction

  ```shell
  fn install --all
  ```

- Only the OpenFuncAsync component needs to be installed

  ```shell
  fn install --openfuncasync
  ```

- Dapr and Knative Serving need to be installed

  ```shell
  fn install --dapr --knative-serving
  ```


## Uninstall

### Scope

- `fn uninstall` will work on v0.4.0 and later versions with the following scope:
  - Uninstall OpenFunction's dependencies
  - Uninstall OpenFunction

### Parameter specifications

> When the following parameters of type bool are used, this means that the setting is true

| Name              | Type | Description                                                  |
| ----------------- | ---- | ------------------------------------------------------------ |
| --verbose         | bool | Show verbose information                                     |
| --dapr            | bool | Using this parameter means that Dapr needs to be uninstalled |
| --keda            | bool | Using this parameter means that KEDA needs to be uninstalled |
| --knative-serving | bool | Using this parameter means that Knative Serving(and default gateway Kourier) needs to be uninstalled |
| --shipwright      | bool | Using this parameter means that ShipWright needs to be uninstalled |
| --cert-manager    | bool | Using this parameter means that Cert Manager needs to be uninstalled |
| --ingress         | bool | Using this parameter means that Ingress Nginx needs to be uninstalled |
| --openfuncasync   | bool | Equivalent to --dapr --keda                                  |
| --all             | bool | Equivalent to --dapr --keda --knative-serving --shipwright --cert-manager --ingress |
| --region-cn       | bool | Uninstall components for Chinese users                       |
| --dry-run         | bool | Used to prompt for the components and their versions to be uninstalled by the current command |

### Example

- Uninstall all dependencies and OpenFunction

  ```shell
  fn uninstall --all
  ```

- Only the OpenFuncAsync component needs to be uninstalled

  ```shell
  fn uninstall --openfuncasync
  ```

- Dapr and Knative Serving need to be uninstalled

  ```shell
  fn uninstall --dapr --knative-serving
  ```

## Demo

### Scope

`fn demo` will work on v0.4.0 and later versions with the following scope:

- Build a quick demo environment using `kind`, which by default will demonstrate synchronous functions(Hello world)

### Parameter specifications

> When the following parameters of type bool are used, this means that the setting is true

| Name        | Type   | Description                                                  |
| ----------- | ------ | ------------------------------------------------------------ |
| --verbose   | bool   | Show verbose information                                     |
| --version   | string | Specify the version of OpenFunction that needs to be installed |
| --region-cn | bool   | For users in China to speed up the download process of dependent components |
| --delete    | bool   | Remove the demo environment                                  |
| --dry-run   | bool   | Used to prompt for the components and their versions to be installed by the current command |

### Example

- Create demo environment

  ```shell
  fn demo --version v0.4.0
  ```

- Remove demo environment

  ```shell
  fn demo --delete
  ```

**Comment by tpiperatgod** [comment]
Perhaps we should consider extending the scope to **v0.3.1**

**Comment by benjaminhuo** [comment]
Use cli to install/uninstall is good.
As I can remember, we've discussed this before. Too many options may not work, what's the exact reason? Can you remember @wanjunlei

**Comment by wanjunlei** [comment]
Do you mean this?
https://github.com/OpenFunction/OpenFunction/pull/153

It had to be fixed.
