### ISSUE TITLE
[Proposal]Progress synchronization update

### ISSUE THREAD

**Issue by wentevill** [OpenFunction/cli#40]
Proposal
- Motivation
  The version gap between the cli and the main repository is too large, and some functions have the wrong starting point. I would recommend that the cli be consistent with version 0.6 of the main repo.
 - Goals
   - [x] Remove ['init'](!https://github.com/OpenFunction/cli/blob/main/pkg/cmd/subcommand/init.go),that shouldn't exist.
   - [x] Use the main repository's client.
   - [x] Feature point support to version 0.6 of the main repository.

**Comment by benjaminhuo** [comment]
Agree, the cli should use the main repo's client and the client in the cli should be removed

**Comment by benjaminhuo** [comment]
@wentevill would you help to make these changes to cli?

**Comment by wentevill** [comment]
yeah,I'd be happy to handle this.

**Comment by wentevill** [comment]
with pull request #41
