### ISSUE TITLE
ofn install --all error

### ISSUE THREAD

**Issue by fansehep** [OpenFunction/cli#44]
When I use ofn install --all , it reports an error.
![2022-05-05_18-05-1651745854](https://user-images.githubusercontent.com/75058860/166904700-3b1171e1-204d-40c4-bb66-3cb74748c6bd.jpg)

**Comment by benjaminhuo** [comment]
should be `ofn install --all`.

Transfer this issue to the cli repo

**Comment by fansehep** [comment]
![2022-05-05_18-05-1651747872](https://user-images.githubusercontent.com/75058860/166909152-2fb4426d-6860-407b-ae77-e9de21822e95.jpg)

**Comment by benjaminhuo** [comment]
You'll need a k8s cluster that you can access

**Comment by fansehep** [comment]
oh thanks
