### ISSUE TITLE
enhance ofn logs functionality

### ISSUE THREAD

**Issue by James-JLC** [OpenFunction/cli#47]
As a developer, I wish I could to see the logs of both build and serving stage, because build stage fails often and it's hard to know the reason. So `ofn logs function_name` should output all logs of build and serving stage, `ofn logs function_name --serving` should output serving logs if user specified.

**Comment by benjaminhuo** [comment]
This is a good proposal. But I think by default `ofn logs function` should output logs for the serving only.
And user can use `ofn logs function --build` to output logs for the build phase.

The reason is that a function can be built once and run many times

**Comment by jilichao** [comment]
hmm... due to build pods are removed automatically once build succeeded, when function is serving, no build logs can be retrieved at all, so I think maybe it makes sense build logs should be output by default when build is running or is failed.

**Comment by jilichao** [comment]
> This is a good proposal. But I think by default `ofn logs function` should output logs for the serving only. And user can use `ofn logs function --build` to output logs for the build phase.
> 
> The reason is that a function can be built once and run many times

hmm... due to build pods are removed automatically once build succeeded, when function is serving, that means no build logs can be retrieved at all, so I think maybe it makes sense build logs should be output by default。

**Comment by James-JLC** [comment]
> This is a good proposal. But I think by default `ofn logs function` should output logs for the serving only. And user can use `ofn logs function --build` to output logs for the build phase.
> 
> The reason is that a function can be built once and run many times

hmm... due to build pods are removed automatically once build succeeded, when function is serving, that means no build logs can be retrieved at all, so I think maybe it makes sense build logs should be output by default.

**Comment by James-JLC** [comment]
`--serving` provides the option that user could see the serving logs only and don't care about build stage.

**Comment by benjaminhuo** [comment]
Make sense, Now I agree with you.
Thanks!

**Comment by benjaminhuo** [comment]
> I created a new PR [#48](https://github.com/OpenFunction/cli/pull/48) to implemented it.

That's great

**Comment by James-JLC** [comment]
I created a new PR [#48](https://github.com/OpenFunction/cli/pull/48) to implemented it.

Could someone review it please. Thank you!

**Comment by benjaminhuo** [comment]
The serving pod will not be started until the build finishes.
So maybe we needn't to add any flag like `--serving` or `--build` at all.
Simply `ofn logs function` is ok, it will fetch build logs when the build is not finished and fetch serving logs when the build finishes and serving started.

What do you think @tpiperatgod @wanjunlei ?

**Comment by wanjunlei** [comment]
> The serving pod will not be started until the build finishes. So maybe we needn't to add any flag like `--serving` or `--build` at all. Simply `ofn logs function` is ok, it will fetch build logs when the build is not finished and fetch serving logs when the build finishes and serving started.
> 
> What do you think @tpiperatgod @wanjunlei ?

Agree.

**Comment by benjaminhuo** [comment]
> The serving pod will not be started until the build finishes. So maybe we needn't to add any flag like `--serving` or `--build` at all. Simply `ofn logs function` is ok, it will fetch build logs when the build is not finished and fetch serving logs when the build finishes and serving started.
> 
> What do you think @tpiperatgod @wanjunlei ?

@jilichao Would you change your PR accordingly?

**Comment by James-JLC** [comment]
Yes, sure! It's done!
